### ISSUE TITLE
Class "Doctrine\DBAL\Driver\AbstractMySQLDriver" not found

### ISSUE THREAD

**Issue by joshmakar** [krlove/eloquent-model-generator#102]
I keep getting this error on a fresh install of Laravel 9.

**Comment by joshmakar** [comment]
I found where others were solving similar issues by running installing dbal with `composer require doctrine/dbal`.

I tried, but it wouldn't work. What eventually did though was removing the Eloquent Model Generator package, reinstalling the doctrine dbal package, and then reinstalling the Eloquent Model Generator package.

**Comment by krlove** [comment]
Hi @joshmakar ,

I've tried following to reproduce it:
```
composer create-project laravel/laravel laravel9
cd laravel9
composer require krlove/eloquent-model-generator
```
then configured the application with DB credentials and run
```
php artisan krlove:generate:model User
```
and it succeeded.

From `composer info doctrine/dbal` I see that it installs correct version 3.5.1, which contains `Doctrine\DBAL\Driver\AbstractMySQLDriver` class.

It there anything else I could do to reproduce this issue?

**Comment by joshmakar** [comment]
I'm not sure. I'm assuming it was just a fluke but wanted to share what my solution was in case anyone else had the same issue.
