### ISSUE TITLE
Update to laravel 10

### ISSUE THREAD

**Issue by vaix-dungpx** [krlove/eloquent-model-generator#108]
Todo update to laravel 10

**Comment by josuechevezUEES** [comment]
Problem 1
    - krlove/eloquent-model-generator[1.0.0, ..., 1.2.7] require laravel/framework ^5.0 -> found laravel/framework[v5.0.0, ..., v5.8.38] but it conflicts with your root composer.json require (^10.0).
    - krlove/eloquent-model-generator[1.3.0, ..., 1.3.2] require illuminate/database ^5.0 -> found illuminate/database[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - krlove/eloquent-model-generator[1.3.3, ..., 1.3.4] require illuminate/database ^5.0 || ^6.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - krlove/eloquent-model-generator 1.3.5 requires illuminate/database ^5.0 || ^6.0 || ^7.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - krlove/eloquent-model-generator[1.3.6, ..., 1.3.7] require illuminate/database ^5.0 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - krlove/eloquent-model-generator 1.3.8 requires illuminate/database ^5.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.
    - krlove/eloquent-model-generator[2.0, ..., 2.0.1] require illuminate/database ^9.0 -> found illuminate/database[v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires krlove/eloquent-model-generator * -> satisfiable by krlove/eloquent-model-generator[1.0.0, ..., 1.3.8, 2.0, 2.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require krlove/eloquent-model-generator:*" to figure out if any version is installable, or "composer require krlove/eloquent-model-generator:^2.1" if you know which you need.

**Comment by TheArKaID** [comment]
Could you please do something for Laravel 10 version. It's been several months. @krlove

**Comment by josuechevezUEES** [comment]
baje la version de php a 8.1 y funciono `composer.json`

**Comment by ricardoaponte** [comment]
Hello, I forked the repo and created a Laravel 10 compatible package. It's in development still but you can give it a try:
https://github.com/rayVenues/eloquent-model-generator

**Comment by DreadfulCode** [comment]
### Here is a fork, working with the latest of Laravel 10.
https://github.com/DreadfulCode/laravel-10-eloquent-model-generator

Packagist link: https://packagist.org/packages/dreadfulcode/eloquent-model-generator

This project is too good to just let die. I am giving a try at maintaining it until the creator resurfaces.

**Comment by krlove** [comment]
Thank you dear people and apologise for my absence. I've released 2.0.2 version which adds Laravel 10 support.
Laravel 11 is going to be released in Q1 2024, I will keep an eye on it and update this library in time.
