### ISSUE TITLE
Connection name not used

### ISSUE THREAD

**Issue by CaptainKant** [krlove/eloquent-model-generator#18]
Hi, thanks for this vendor,
The option --connection seems to not be used in processors however

```
$this->databaseManager->connection()  //instead of 
$this->databaseManager->connection($someConfigValue)

```
So only the main database can be directly worked on it

**Comment by krlove** [comment]
Hi @CaptainKant,

thanks for your contribution, the issue is fixed in version 1.2.3 in this [commit](https://github.com/krlove/eloquent-model-generator/commit/0bfc62432cddc4f9f800f8c81bb159e57e66ca17)
