### ISSUE TITLE
RelationProcessor has wrong priority

### ISSUE THREAD

**Issue by CanisLupusXenonis** [krlove/eloquent-model-generator#19]
`RelationProcessor` depends on work from `NamespaceProcessor`, but both have priority 5. Due to how `usort` works and due to the initial order of the Processors, this deterministically works at the first call to `EloquentModelBuilder.createModel`, but throws at the second.

Can be fixed by increasing `RelationProcessor`'s priority to e.g. 6.

**Comment by krlove** [comment]
Hi @CanisLupusXenonis,

thanks for contribution, the issue is fixed in version 1.2.3 in this [commit](https://github.com/krlove/eloquent-model-generator/commit/dd494a30e2259d9477a7665f37bacbafe27cdd14)
