### ISSUE TITLE
Using Outside of Laravel

### ISSUE THREAD

**Issue by jeffmthomas** [krlove/eloquent-model-generator#20]
I use eloquent capsules on my custom framework and I'm wondering if there is a way that I can use this natively in PHP to generate eloquent models without using the cli?

**Comment by krlove** [comment]
@jeffmthomas you can try forking the library and use `Krlove\EloquentModelGenerator\EloquentModelBuilder::createModel` as the entry point. Also you'll probably need to extend `Krlove\EloquentModelGenerator\Config` class to be able to provide your own configuration for the builder.
