### ISSUE TITLE
update model: Fatal error: Call to a member function tablesExist() 

### ISSUE THREAD

**Issue by ant-ia** [krlove/eloquent-model-generator#21]
Hello,
When I try to update the model with:

php artisan krlove:generate:model NameModel --table-name=name_table

I get this error:

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to a member function tablesExist() on null 

How can I turn it around?
Thank you

**Comment by krlove** [comment]
You should take a closer look on the first line of `ExistenceCheckerProcessor::process` method. Make sure `getDoctrineSchemaManager` return a proper instance of `AbstractSchemaManager`.
