### ISSUE TITLE
Error when table does not have Primary Key

### ISSUE THREAD

**Issue by double-reinbows** [krlove/eloquent-model-generator#23]
I have a table which stores image URLs. This table does not have its own Primary Key (id) but it does have a Foreign Key (id of a different table). the model generator returns this error when the table does not have a PK:

[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function getColumns() on null 

Personally, I think it should be able to handle PKless tables....

Thanks!

**Comment by krlove** [comment]
Hi @double-reinbows,

Can you add more info on this issue? In particular can you provide your database structure (at least table(s) you are trying to generate model(s) for) and command call (what parameters do you supply as an arguments)?

**Comment by double-reinbows** [comment]
[migrations.zip](https://github.com/krlove/eloquent-model-generator/files/1060417/migrations.zip)
I think I know the problem... I create all of my tables before I create the foreign keys so when your generator reads my migration files, it thinks there's an error because I'm creating tables without any keys.

Maybe if I create my Foreign Key inside my create_table migration, it will work?

**Comment by jcollinsaceoneprod** [comment]
You have to be correct. This is what I was thinking.
