### ISSUE TITLE
db_types option in config file doesn't work

### ISSUE THREAD

**Issue by psystems** [krlove/eloquent-model-generator#25]
Hello!

Thank you for your package! It is cool thing, but I found little problem.

When I try to use db_types and connection in config eloquent_model_generator then it gives an error.
                                                                                                   
  [Doctrine\DBAL\DBALException]                                                                    
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.  

But if I don't use connection option and change db name in default connection, then it works correct.

I tried different cases use connection in cli args and configs, results are repeated, then it doesn't see db_types array, for example, enum => string.

Best regards,
Ruslan

**Comment by krlove** [comment]
Hi @psystems 

Thanks for this issue, good catch!
I've applied a fix (v1.2.4), can you please check everything works now?
