### ISSUE TITLE
Custom Primary Key

### ISSUE THREAD

**Issue by krizztianz** [krlove/eloquent-model-generator#26]
Hey there,

I used custom primarykey name instead of **id** in my tables. 
In Eloquent we used `public $primaryKey ` property to set primarykey name to match in the table.
But it seems your generator doesn't generate `public $primaryKey = "{{ custom_primarykey_name }}";`

It would be awesome if you have this feature.

Thank you,
Regards

**Comment by krlove** [comment]
Hey @krizztianz ,

Thanks for your suggestion!

Checkout version 1.2.5 with support of custom primary keys, key types and incrementing properties support.
