### ISSUE TITLE
Support for Schema Name?

### ISSUE THREAD

**Issue by jhjm32087** [krlove/eloquent-model-generator#27]
Does this project support for example schema_name.table_name?

**Comment by wcadena** [comment]
ademas para que mapee las tablas desde MSQLSERVER se realiza un cambio que ya se solicito a proveedor de servicio, cambiar
 *
 *  src/Processor/ExistenceCheckerProcessor.php
 * +        $replaced_table = str_replace_first('dbo.', '', $model->getTableName());
 * +        //sql server
 * +        if (!$schemaManager->tablesExist($prefix . $replaced_table)) {
 *
 *
