### ISSUE TITLE
[ASK] Laravel 5.5 Compatibility

### ISSUE THREAD

**Issue by krizztianz** [krlove/eloquent-model-generator#29]
Hey @krlove 
Laravel 5.5 has been released, does your package already compatible with it?

Thank you...

**Comment by AntoninSlejska** [comment]
I get the following error message in Laravel 5.5:
`[ReflectionException]
  Method Krlove\EloquentModelGenerator\Command\GenerateModelCommand::handle() does not exist`

**Comment by krlove** [comment]
Fixed in version 1.2.6.
