### ISSUE TITLE
GenerateModelCommand:handle() does not exist

### ISSUE THREAD

**Issue by SolidTerre** [krlove/eloquent-model-generator#31]
Hi,

I am using your package for a pretty long time now, it's really handy to have!

Unfortunately, I recently created a new project in the latest Laravel (5.5) and keep getting an error on the krlove command as you can see below.

Is this due to Laravel 5.5, or am I missing something?

Thank you !

![image](https://user-images.githubusercontent.com/8171049/31349832-217a1872-ad25-11e7-804a-c36e90795533.png)

**Comment by krlove** [comment]
Hi @SolidTerre 

This issue is fixed in the latest release.
