### ISSUE TITLE
is it possible to run the package for all tables ? 

### ISSUE THREAD

**Issue by badrshs** [krlove/eloquent-model-generator#38]
Hi, 
I was looking inside the documentation but I couldn't find such thing . is it possible to generate for whole database at once ?
I dont want to add the table one by one
suggestion command

`php artisan krlove:generate:all`

**Comment by krlove** [comment]
Hi Badr,
I'm going to work on it next.
Keep you informed!
Thanks!

**Comment by munizeverton** [comment]
@krlove Are you already working on it?
I can offer help

**Comment by tprj29** [comment]
I created #46 for myself maybe it helps out one of u.

**Comment by yurik94** [comment]
> I created #46 for myself maybe it helps out one of u.
> 
> ```
> <?php
> 
> namespace App\Console\Commands;
> 
> 
> use Illuminate\Console\Command;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\DB;
> use Illuminate\Support\Str;
> 
> class GenerateAllModels extends Command
> {
>     /**
>      * The name and signature of the console command.
>      *
>      * @var string
>      */
>     protected $signature = 'krlove:generate:all-models';
> 
>     /**
>      * The console command description.
>      *
>      * @var string
>      */
>     protected $description = 'Generate all models';
> 
>     /**
>      * Execute the console command.
>      *
>      * @return mixed
>      */
>     public function handle()
>     {
>         $tables = DB::select('SHOW TABLES');
>         $databaseName = config('database.connections.'.config('database.default').'.database');
>         $tables = collect($tables);
>         $tables = $tables->pluck('Tables_in_'.$databaseName);
>         foreach($tables as $table)
>         {
>             if($table === 'migrations') continue;
>             $className = Str::camel(Str::singular($table));
>             $className = ucfirst($className);
>             Artisan::call('krlove:generate:model', ['class-name' => $className, '--table-name' => $table]);
>         }
>     }
> }
> ```

Thanks, you saved me some minutes 😄

**Comment by xZero707** [comment]
@tprj29 I would suggest using 
```php
DB::connection()->getDoctrineSchemaManager()->listTableNames();
```
It requires doctrine/dbal, but that's already used. 

That way you get string[]

**Comment by omar-b98** [comment]
> I created #46 for myself maybe it helps out one of u.
> 
> ```
> <?php
> 
> namespace App\Console\Commands;
> 
> 
> use Illuminate\Console\Command;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\DB;
> use Illuminate\Support\Str;
> 
> class GenerateAllModels extends Command
> {
>     /**
>      * The name and signature of the console command.
>      *
>      * @var string
>      */
>     protected $signature = 'krlove:generate:all-models';
> 
>     /**
>      * The console command description.
>      *
>      * @var string
>      */
>     protected $description = 'Generate all models';
> 
>     /**
>      * Execute the console command.
>      *
>      * @return mixed
>      */
>     public function handle()
>     {
>         $tables = DB::select('SHOW TABLES');
>         $databaseName = config('database.connections.'.config('database.default').'.database');
>         $tables = collect($tables);
>         $tables = $tables->pluck('Tables_in_'.$databaseName);
>         foreach($tables as $table)
>         {
>             if($table === 'migrations') continue;
>             $className = Str::camel(Str::singular($table));
>             $className = ucfirst($className);
>             Artisan::call('krlove:generate:model', ['class-name' => $className, '--table-name' => $table]);
>         }
>     }
> }
> ```

i was looking for this one ,i like the way you made it,genius ,thank you

**Comment by DevGonga** [comment]
thank you, perfect!

**Comment by DevGonga** [comment]
> I created #46 for myself maybe it helps out one of u.
> 
> ```
> <?php
> 
> namespace App\Console\Commands;
> 
> 
> use Illuminate\Console\Command;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\DB;
> use Illuminate\Support\Str;
> 
> class GenerateAllModels extends Command
> {
>     /**
>      * The name and signature of the console command.
>      *
>      * @var string
>      */
>     protected $signature = 'krlove:generate:all-models';
> 
>     /**
>      * The console command description.
>      *
>      * @var string
>      */
>     protected $description = 'Generate all models';
> 
>     /**
>      * Execute the console command.
>      *
>      * @return mixed
>      */
>     public function handle()
>     {
>         $tables = DB::select('SHOW TABLES');
>         $databaseName = config('database.connections.'.config('database.default').'.database');
>         $tables = collect($tables);
>         $tables = $tables->pluck('Tables_in_'.$databaseName);
>         foreach($tables as $table)
>         {
>             if($table === 'migrations') continue;
>             $className = Str::camel(Str::singular($table));
>             $className = ucfirst($className);
>             Artisan::call('krlove:generate:model', ['class-name' => $className, '--table-name' => $table]);
>         }
>     }
> }
> ```

thank you, perfect!

**Comment by jechaviz** [comment]
where to save this file?

**Comment by fabriciogonga0** [comment]
run on terminal
`php artisan make: command models`
then go to the app/console/comands folder.

open the 'models' file and replace it with the code.

now run in `php artisan krlove: generate: all-models`

**Comment by fabriciogonga0** [comment]
run on terminal
`php artisan make:command models`
then go to the app/console/comands folder.

open the 'models' file and replace it with the code.

now run in `php artisan krlove:generate:all-models`

**Comment by kephren226** [comment]
> 
> 
> I created #46 for myself maybe it helps out one of u.
> 
> ```
> <?php
> 
> namespace App\Console\Commands;
> 
> 
> use Illuminate\Console\Command;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\DB;
> use Illuminate\Support\Str;
> 
> class GenerateAllModels extends Command
> {
>     /**
>      * The name and signature of the console command.
>      *
>      * @var string
>      */
>     protected $signature = 'krlove:generate:all-models';
> 
>     /**
>      * The console command description.
>      *
>      * @var string
>      */
>     protected $description = 'Generate all models';
> 
>     /**
>      * Execute the console command.
>      *
>      * @return mixed
>      */
>     public function handle()
>     {
>         $tables = DB::select('SHOW TABLES');
>         $databaseName = config('database.connections.'.config('database.default').'.database');
>         $tables = collect($tables);
>         $tables = $tables->pluck('Tables_in_'.$databaseName);
>         foreach($tables as $table)
>         {
>             if($table === 'migrations') continue;
>             $className = Str::camel(Str::singular($table));
>             $className = ucfirst($className);
>             Artisan::call('krlove:generate:model', ['class-name' => $className, '--table-name' => $table]);
>         }
>     }
> }
> ```

Any idea to make it run with Postgresql ?

**Comment by lengaltd** [comment]
<?php

namespace App\Http\Controllers;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class GiiiController extends Controller
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'krlove:generate:all-models';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate all models';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function allModels()
    {

        $tables = DB::connection()->getDoctrineSchemaManager()->listTableNames();
        $databaseName = config('database.connections.'. config('database.default') .'.database');
        $tables = collect($tables);

        foreach($tables as $table)
        {

            if( ( $table === 'migrations' ) || ( $table === 'users' ) || ( $table === 'user' ) ) continue ;

            $className = Str::camel(Str::singular($table));
            $className = ucfirst($className);

            Artisan::call(
            'krlove:generate:model', 
            [
                'class-name' => $className, '--table-name' => $table, '--output-path' => 'Models', '--namespace' => 'App\\Models'
            ]);

        }

        return response()->json([
            're' => [
                $databaseName, $tables
            ]
        ]);

    }

}

**Comment by krlove** [comment]
Version 2.0.0 finally has it.
