### ISSUE TITLE
Disable pluralization

### ISSUE THREAD

**Issue by phiter** [krlove/eloquent-model-generator#47]
Is there any way to run this without pluralizing the table and relationship names?

The database we have has the table names in portuguese so the way it pluralizes the names is kinda weird.

I know it's a Laravel convention to use it that way, but I'd like to generate the classes with the same names as the tables.

**Comment by xZero707** [comment]
I think that would be redundant since you can use **--table-name** argument (or simply -tn). 
Eg. --table-name="user"

**Comment by Elendil92** [comment]
It is not redundant. My tables are in spanish, and on the .php autogenerated file, the model relations are wrongs with this plurarization.

**Comment by xZero707** [comment]
You can do this:
```
--table-name="user"
--table-name="cat"
--table-name="dog"
```
As long as these are supplied, these values are used instead of auto-pluralization. 
Values can be in your language, obviously, so I don't see the problem. 

I agree that having an argument to disable pluralization completely would be practical.

**Comment by Elendil92** [comment]
> 
> 
> You can do this:
> 
> ```
> --table-name="user"
> --table-name="cat"
> --table-name="dog"
> ```
> 
> As long as these are supplied, these values are used instead of auto-pluralization.
> Values can be in your language, obviously, so I don't see the problem.
> 
> I agree that having an argument to disable pluralization completely would be practical.

I did that. And in the generated files I found incrouenses (I'm Cuban, sorry for bad writing) pointing to inextisting files becaus of plurarization. I'm not critizising your work (i't saved me a lot of work my self), I managed to solved out by naming in singular my databases.
Sorry for not making a capture of the results. It was principally on the relations parts.
