### ISSUE TITLE
cannot generator

### ISSUE THREAD

**Issue by thanhdevapp** [krlove/eloquent-model-generator#5]
I run command but get message There are no commands defined in the "krlove:generate" namespace.

**Comment by krlove** [comment]
@thanhdevapp Have you registered `GeneratorServiceProvider` as mentioned at Step 2?

**Comment by johgh** [comment]
I have the same problem: "There are no commands defined in the "krlove:generate" namespace."

I put the line mentioned at step 2 in the file config/app.php. Am I doing something wrong?

**Comment by yeisonkamilo** [comment]
en confi/app agregas Krlove\EloquentModelGenerator\Provider\GeneratorServiceProvider::class, in Package Service Providers... line 167

**Comment by Dom911** [comment]
Hi I have the same issue  "There are no commands defined in the "krlove:generate" namespace."
In verbose mode I get this answer:

`php artisan -v krlove:generate:model Department --table-name=llx_c_departements --namespace=App`

`In Application.php line 612:
                                                                     
  [Symfony\Component\Console\Exception\NamespaceNotFoundException]   
  There are no commands defined in the "krlove:generate" namespace.  
                                                                     

Exception trace:
  at /var/www/html/custom/sci/sciLaravel/vendor/symfony/console/Application.php:612
 Symfony\Component\Console\Application->findNamespace() at /var/www/html/custom/sci/sciLaravel/vendor/symfony/console/Application.php:663
 Symfony\Component\Console\Application->find() at /var/www/html/custom/sci/sciLaravel/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/custom/sci/sciLaravel/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /var/www/html/custom/sci/sciLaravel/vendor/laravel/framework/src/Illuminate/Console/Application.php:94
 Illuminate\Console\Application->run() at /var/www/html/custom/sci/sciLaravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/custom/sci/sciLaravel/artisan:37`
