### ISSUE TITLE
 ErrorException  : usort() expects parameter 1 to be array, object given

### ISSUE THREAD

**Issue by karelbyte** [krlove/eloquent-model-generator#50]
php artisan krlove:generate:model User

   ErrorException  : usort() expects parameter 1 to be array, object given

  at /var/www/html/socialcore/vendor/krlove/eloquent-model-generator/src/EloquentModelBuilder.php:58

help!

**Comment by wcadena** [comment]
Hi
What is your data base?


Saludos
Wagner Cadena
Enviado desde mi iPhone

El 28 feb. 2019, a la(s) 18:59, Karel Puerto Diaz <notifications@github.com<mailto:notifications@github.com>> escribió:


php artisan krlove:generate:model User

ErrorException : usort() expects parameter 1 to be array, object given

at /var/www/html/socialcore/vendor/krlove/eloquent-model-generator/src/EloquentModelBuilder.php:58

help!

**Comment by karelbyte** [comment]
estoy usando postgres

**Comment by krlove** [comment]
Fixed in [this PR](https://github.com/krlove/eloquent-model-generator/pull/49)
