### ISSUE TITLE
Enum problem still exists

### ISSUE THREAD

**Issue by bzstabryn** [krlove/eloquent-model-generator#54]
Solution described [here](https://github.com/krlove/eloquent-model-generator#registring-custom-database-types) does not work anymore for Lumen 5.8.4
eloquent-model-generator version: v1.2.7
error message: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

**Comment by phpguru** [comment]
@bzstabryn This is not an ideal workaround, I know, but the solution you linked to works for Laravel 5.6 - you could fire up a `laravel new modelgen` project and just use it for krlove, then move your models into your Lumen project.

**Comment by bzstabryn** [comment]
Thanks @phpguru. I found another workaround - I am just modifying parent config in "/vendor/krlove/eloquent-model-generator/src/Resources/config.php"

**Comment by j3rrey** [comment]
bump

**Comment by phpguru** [comment]
@j3rrey [answered](https://github.com/krlove/eloquent-model-generator/issues/7#issuecomment-235281787) by krlove - look [here](https://github.com/krlove/eloquent-model-generator/issues/6#issuecomment-233077476)

**Comment by lintaba** [comment]
you can bypass it with running
```php
DB::connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
```
for me it worked to run the commands from tinker, and with `Artisan::call("krlove:generate:model ...");` . Its a bit hacky, but works, and you usually need this only once.

**Comment by nbtafelberg** [comment]
^ This works - i literally added it to the routes.php file in Laravel and it all started working - incidentally I was having the same trouble with the bit field I'm working with a massive MySQL database so database modifications are not possible.

DB::connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('bit', 'boolean');

**Comment by sudofox** [comment]
> `Artisan::call("krlove:[...]` from tinker

I end up with this in tinker:

```
>>> Artisan::call("krlove:generate:model Sensor");
PHP Error:  Class 'Artisan' not found in <snip>eval()'d code on line 1
```

Any ideas? This is on Lumen

```
laravel/lumen-framework": "^8.3.1"
```
