### ISSUE TITLE
enum type can not generate model

### ISSUE THREAD

**Issue by michaelqxd** [krlove/eloquent-model-generator#6]
one enum type in my database, if i remove it, then it's work fine,  if i add then it can not work.

 [Doctrine\DBAL\DBALException]
 Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform
  may not support it.

**Comment by krlove** [comment]
Hi @michaelqxd,

Thank you for your feedback.

Eloquent Model Generator uses Doctrine internally which does not "know" about `enum` type. You have to register `enum` type at Doctrine's Database Platform before using Generator.

I have created a fix for this issue and published a new version 1.1.0.
Please refer [this chapter of documentation](https://github.com/krlove/eloquent-model-generator#registring-custom-database-types) which describes resolving of the issue.
