### ISSUE TITLE
[feature request] Add support for json/jsonb casts property creation

### ISSUE THREAD

**Issue by RaiMX** [krlove/eloquent-model-generator#61]
Can you please add support for json/jsonb casts property creation.
For example, a table has column 'meta' which is a jsonb data type.
When generating model, with additional option, generator would add 
`protected $casts = [
        'meta' => 'array',
    ];
`to the model

**Comment by krlove** [comment]
Hi @RaiMX ,

Thank you for the feedback. Feature you're requesting indeed makes sense. Before adding it I'd like to be sure it would be beneficial for others. I'm going to pin the issue to the repository and see if it collects **20+ thumbs up** from the community. When that happens, I implement it.

In a meanwhile feel free to provide more detailed description for the feature. It will help users understand it better and vote for it.

**Comment by BaraoVlask** [comment]
It will be way better if we can add our own doctrine types types it will be more flexible and can reduce future issues

**Comment by krlove** [comment]
Unpinned issue due to low activity
