### ISSUE TITLE
is it possible to general all models at once?

### ISSUE THREAD

**Issue by fgonga** [krlove/eloquent-model-generator#74]
There is something to generate:
php artisan krlove:generate:everything

**Comment by marciobera** [comment]
> There is something to generate:
> php artisan krlove:generate:everything

afaik not yet by default, but https://github.com/krlove/eloquent-model-generator/issues/38#issuecomment-431660047 should help with that for a while

**Comment by krlove** [comment]
Version 2.0.0. finally contains this functionality.
