### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by MilesHart** [krlove/eloquent-model-generator#80]
Anyone else getting this?

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by ty-huynh** [comment]
@MilesHart hope this help

```
COMPOSER_MEMORY_LIMIT=-1 composer require --dev krlove/eloquent-model-generator
```

**Comment by krlove** [comment]
Closing since it is not related to this lib but rather to composer memory issues
