### ISSUE TITLE
DBAL 3 Support

### ISSUE THREAD

**Issue by kevindb** [krlove/eloquent-model-generator#82]
Laravel 8 supports DBAL 3, released 2020-11-15. Eloquent Model Generator still requires DBAL ^2.5. Are there any plans to support DBAL 3?

https://github.com/laravel/framework/pull/35236
https://github.com/doctrine/dbal/releases/tag/3.0.0

Thank you for the awesome tool! It is very helpful in making models match the database structure.

**Comment by MahdiJouni1998** [comment]
I also have an issue with DBAL's v3.0 on Laravel 8, any thing I can do about it?

**Comment by krlove** [comment]
Added support in [version 1.3.7](https://github.com/krlove/eloquent-model-generator/releases/tag/1.3.7)
