### ISSUE TITLE
Class PDOMySql\Driver not found

### ISSUE THREAD

**Issue by kalucky0** [krlove/eloquent-model-generator#83]
````
Symfony\Component\Debug\Exception\FatalThrowableError : Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

at vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:64
    60 |      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
    61 |      */
    62 |     protected function getDoctrineDriver()
    63 |     {
  > 64 |         return new DoctrineDriver;
    65 |     }
    66 | }
    67 |

  Exception trace:

  1   Illuminate\Database\MySqlConnection::getDoctrineDriver()
      vendor\laravel\framework\src\Illuminate\Database\Connection.php:892

  2   Illuminate\Database\Connection::getDoctrineSchemaManager()
      vendor\krlove\eloquent-model-generator\src\Processor\ExistenceCheckerProcessor.php:35

  Please use the argument -v to see more details.

````
I tried downgrading DBAL to v2.0 but then I get other errors.

**Comment by jfhernandeze** [comment]
Any luck?

I am getting:

  Error 

  Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

  at vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:64
    60|      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
    61|      */
    62|     protected function getDoctrineDriver()
    63|     {
  > 64|         return new DoctrineDriver;
    65|     }
    66| }
    67| 

      +19 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))



composer.json;

"require": {
        "php": "^7.2.5",
        "barryvdh/laravel-dompdf": "^0.8.6",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "netojose/laravel-bootstrap-4-forms": "^3.0",
        "simplesoftwareio/simple-qrcode": "^4.2",
        "tymon/jwt-auth": "^1.0",
        "venturecraft/revisionable": "^1.34",
        "yajra/laravel-datatables-oracle": "^9.10"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "krlove/eloquent-model-generator": "^1.3",


jfhernandeze@MacBook-Pro-de-Jose kef-admin2 % php -v
PHP 7.3.25 (cli) (built: Nov 30 2020 14:36:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
