### ISSUE TITLE
Support for MS SQL Server

### ISSUE THREAD

**Issue by izzy1333** [krlove/eloquent-model-generator#85]
I am trying to use the Eloquent Model Generator with MS SQL Server and am getting the error "Unknown database type timestamp requested, Doctrine\DBAL\Platforms\SQLServer2012Platform may not support it". How can I resolve this ..  to add a custom mapping type ? Thanks

**Comment by krlove** [comment]
Indeed, `timestamp` isn't supported out of the box, you should add custom casting to `db_types` config.
