### ISSUE TITLE
Model has been created with a wrong name

### ISSUE THREAD

**Issue by brunoramonalmeida** [krlove/eloquent-model-generator#9]
Hi,

firstly, congratulations for the contribution, this project is very interesting and it helps a lot. 

The issue is: a tried to create a Model from a table called "Conta". However, the file created and the reference for this table was called from "Contum". I don't know if it's a bug.

Thanks in advice.

**Comment by krlove** [comment]
Hey @brunoramonalmeida, I appreciate you have positive impressions of this project.

What arguments and options do you supply to the command? Can you show how you call it?

**Comment by brunoramonalmeida** [comment]
I only provided the "table-name" argument, as follows:
`php artisan krlove:generate:model Conta --table-name=conta`

**Comment by krlove** [comment]
It worked fine for me, I couldn't reproduce the issue.
Table name is resolved directly from the option `table-name` if it is supplied.
Can you share more information on the issue?
