### ISSUE TITLE
Autodiscovery in version 2

### ISSUE THREAD

**Issue by buzkall** [krlove/eloquent-model-generator#92]
It's possible to bring back the autodiscovery to version 2?
Adding manually the provider to app.php makes it imposible to use composer install --no-dev in production

**Comment by buzkall** [comment]
I've created a pull request #93

**Comment by krlove** [comment]
Thank you @buzkall , I've restored it in https://github.com/krlove/eloquent-model-generator/releases/tag/2.0.1
