### ISSUE TITLE
Override Mass Assignment

### ISSUE THREAD

**Issue by ty3sc** [krlove/eloquent-model-generator#94]
Hi,

Thanks for this library, it's really helpful for quickly scaffolding projects.

Is there a way to override the `fillable` or `guarded` properties from the command line?

For example, I would like to create my models with `$guarded = []`. Is that possible?

Thanks :)

**Comment by krlove** [comment]
Hi @ty3sc ,

This is definitely possible - you could introduce [custom processor](https://github.com/krlove/eloquent-model-generator#customization), that adds these fields to the model.
