### ISSUE TITLE
laravel7.30,Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

### ISSUE THREAD

**Issue by BlueMantaRay** [krlove/eloquent-model-generator#96]
composer config:
  "require": {
        "php": "^7.2.5|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3.1|^7.0.1",
        "laravel/framework": "^7.29",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fakerphp/faker": "^1.9.1",
        "krlove/eloquent-model-generator": "^1.3",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.3",
        "phpunit/phpunit": "^8.5.8|^9.3.3"
    }

Error Message:
  Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

  at vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:64
    60|      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
    61|      */
    62|     protected function getDoctrineDriver()
    63|     {
  > 64|         return new DoctrineDriver;
    65|     }
    66| }
    67|

**Comment by krlove** [comment]
You're using `laravel/framework` version 7, which is incompatible with version 2 of this library. You could try using version 1 instead.
